// This file was generated by SquareLine Studio and integrated for the course app.

#include "../ui.h"

static void set_panel_style(lv_obj_t * obj, uint32_t bg, uint32_t border)
{
    lv_obj_set_style_radius(obj, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(bg), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(obj, lv_color_hex(border), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(obj, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void set_button_style(lv_obj_t * obj, uint32_t bg)
{
    lv_obj_set_style_radius(obj, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(bg), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(obj, lv_color_hex(0x102033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(obj, lv_color_hex(0x9EB8DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xF4F7FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TitleLabel, 760);
    lv_obj_set_height(ui_TitleLabel, 34);
    lv_obj_set_x(ui_TitleLabel, 20);
    lv_obj_set_y(ui_TitleLabel, 14);
    lv_label_set_long_mode(ui_TitleLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_TitleLabel, "嘎嘎鸭智能助手");
    lv_obj_set_style_text_align(ui_TitleLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TitleLabel, lv_color_hex(0x14213D), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AnswerPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_AnswerPanel, 760);
    lv_obj_set_height(ui_AnswerPanel, 238);
    lv_obj_set_x(ui_AnswerPanel, 20);
    lv_obj_set_y(ui_AnswerPanel, 62);
    lv_obj_remove_flag(ui_AnswerPanel, LV_OBJ_FLAG_SCROLLABLE);
    set_panel_style(ui_AnswerPanel, 0xFFF4CC, 0xE0BC63);

    ui_TextArea2 = lv_textarea_create(ui_AnswerPanel);
    lv_obj_set_width(ui_TextArea2, 736);
    lv_obj_set_height(ui_TextArea2, 214);
    lv_obj_set_x(ui_TextArea2, 0);
    lv_obj_set_y(ui_TextArea2, 0);
    lv_textarea_set_placeholder_text(ui_TextArea2, "模型的回答数据");
    lv_textarea_set_text(ui_TextArea2, "模型的回答数据");
    lv_textarea_set_one_line(ui_TextArea2, false);
    lv_textarea_set_cursor_click_pos(ui_TextArea2, false);
    lv_obj_set_style_bg_opa(ui_TextArea2, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TextArea2, lv_color_hex(0x241A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_TextArea2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 140);
    lv_obj_set_height(ui_Button1, 58);
    lv_obj_set_x(ui_Button1, 20);
    lv_obj_set_y(ui_Button1, 322);
    set_button_style(ui_Button1, 0xD9E9FF);
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);

    ui_Label2 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "语音输入");

    ui_TextArea1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea1, 420);
    lv_obj_set_height(ui_TextArea1, 58);
    lv_obj_set_x(ui_TextArea1, 180);
    lv_obj_set_y(ui_TextArea1, 322);
    lv_textarea_set_one_line(ui_TextArea1, true);
    lv_textarea_set_placeholder_text(ui_TextArea1, "问题");
    lv_textarea_set_text(ui_TextArea1, "");
    lv_obj_set_style_radius(ui_TextArea1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0xBAC7D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0x102033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea1, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0x7D8A99), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_TextArea1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 160);
    lv_obj_set_height(ui_Button2, 58);
    lv_obj_set_x(ui_Button2, 620);
    lv_obj_set_y(ui_Button2, 322);
    set_button_style(ui_Button2, 0xE5F0FF);
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);

    ui_Label3 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "发送按钮");

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, 760);
    lv_obj_set_height(ui_Label1, 34);
    lv_obj_set_x(ui_Label1, 20);
    lv_obj_set_y(ui_Label1, 404);
    lv_label_set_long_mode(ui_Label1, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Label1, "就绪：点击语音输入，识别后点击发送按钮");
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x394B5F), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
}
