// This file was generated by SquareLine Studio and integrated for the course app.

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

lv_obj_t * ui_Screen1;
lv_obj_t * ui_TitleLabel;
lv_obj_t * ui_AnswerPanel;
lv_obj_t * ui_TextArea2;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_TextArea1;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label1;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif

///////////////////// FUNCTIONS ////////////////////

void ui_event_Button1(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        RecordAudio(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        SendQuestion(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
