// This file was generated by SquareLine Studio and integrated for the course app.

#include "ui.h"

#include <pthread.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#define BAIDU_ASR_URL       "http://vop.baidu.com/pro_api"
#define BAIDU_DEV_PID       "80001"
#define BAIDU_CUID          "gec6818"
#define BAIDU_TOKEN         "24.8f82fd86a351aa61268aeb0fb74ca0e1.2592000.1782806618.282335-123532484"

#define COZE_API_URL        "https://api.coze.cn/v3/chat"
#define COZE_TOKEN          "pat_Ua2cJ7Ea7ERnxMaeyRwKZNTLcElTx0xrZx7jIbGlykwDP0jaNP5FKtTucsP6c5ET"
#define COZE_BOT_ID         "7584083392263192618"
#define COZE_USER_ID        "gec6818_user"

#define AUDIO_FILE          "/tmp/assistant_question.wav"
#define STEREO_AUDIO_FILE   "/tmp/assistant_question_stereo.wav"
#define RECORD_ERROR_LOG    "/tmp/assistant_arecord.log"
#define BAIDU_RESPONSE_LOG  "/tmp/baidu_asr_response.txt"
#define COZE_RESPONSE_LOG   "/tmp/coze_response.txt"
#define RECORD_SECONDS      5
#define BUILD_MARK          "REC_FIX_COZE_PARSE_20260607"

static pthread_mutex_t state_lock = PTHREAD_MUTEX_INITIALIZER;
static bool app_busy = false;
static bool dirty_status = false;
static bool dirty_question = false;
static bool dirty_answer = false;
static char pending_status[256];
static char pending_question[1024];
static char pending_answer[4096];
static const char assistant_build_mark[] = BUILD_MARK;

static void append_text(char * dst, size_t dst_size, const char * src)
{
    size_t used;
    size_t avail;

    if(dst_size == 0 || src == NULL) {
        return;
    }

    used = strlen(dst);
    if(used >= dst_size - 1) {
        return;
    }

    avail = dst_size - used - 1;
    strncat(dst, src, avail);
}

static void queue_status(const char * text)
{
    pthread_mutex_lock(&state_lock);
    snprintf(pending_status, sizeof(pending_status), "%s", text);
    dirty_status = true;
    pthread_mutex_unlock(&state_lock);
}

static void queue_question(const char * text)
{
    pthread_mutex_lock(&state_lock);
    snprintf(pending_question, sizeof(pending_question), "%s", text);
    dirty_question = true;
    pthread_mutex_unlock(&state_lock);
}

static void queue_answer(const char * text)
{
    pthread_mutex_lock(&state_lock);
    snprintf(pending_answer, sizeof(pending_answer), "%s", text);
    dirty_answer = true;
    pthread_mutex_unlock(&state_lock);
}

static bool try_begin_job(void)
{
    bool ok = false;

    pthread_mutex_lock(&state_lock);
    if(!app_busy) {
        app_busy = true;
        ok = true;
    }
    pthread_mutex_unlock(&state_lock);

    return ok;
}

static void finish_job(void)
{
    pthread_mutex_lock(&state_lock);
    app_busy = false;
    pthread_mutex_unlock(&state_lock);
}

static bool is_blank_text(const char * text)
{
    if(text == NULL) {
        return true;
    }

    while(*text) {
        if(*text != ' ' && *text != '\t' && *text != '\r' && *text != '\n') {
            return false;
        }
        text++;
    }

    return true;
}

static char * duplicate_text(const char * text)
{
    size_t len;
    char * copy;

    if(text == NULL) {
        return NULL;
    }

    len = strlen(text) + 1;
    copy = (char *)malloc(len);
    if(copy != NULL) {
        memcpy(copy, text, len);
    }

    return copy;
}

static int hex_value(char ch)
{
    if(ch >= '0' && ch <= '9') return ch - '0';
    if(ch >= 'a' && ch <= 'f') return ch - 'a' + 10;
    if(ch >= 'A' && ch <= 'F') return ch - 'A' + 10;
    return -1;
}

static bool read_hex4(const char * text, unsigned int * codepoint)
{
    unsigned int value = 0;

    for(int i = 0; i < 4; i++) {
        int digit = hex_value(text[i]);
        if(digit < 0) {
            return false;
        }
        value = (value << 4) | (unsigned int)digit;
    }

    *codepoint = value;
    return true;
}

static void append_utf8(char * out, size_t out_size, size_t * used, unsigned int cp)
{
    if(out_size == 0 || *used >= out_size - 1) {
        return;
    }

    if(cp <= 0x7F) {
        out[(*used)++] = (char)cp;
    }
    else if(cp <= 0x7FF && *used + 2 < out_size) {
        out[(*used)++] = (char)(0xC0 | (cp >> 6));
        out[(*used)++] = (char)(0x80 | (cp & 0x3F));
    }
    else if(cp <= 0xFFFF && *used + 3 < out_size) {
        out[(*used)++] = (char)(0xE0 | (cp >> 12));
        out[(*used)++] = (char)(0x80 | ((cp >> 6) & 0x3F));
        out[(*used)++] = (char)(0x80 | (cp & 0x3F));
    }
    else if(cp <= 0x10FFFF && *used + 4 < out_size) {
        out[(*used)++] = (char)(0xF0 | (cp >> 18));
        out[(*used)++] = (char)(0x80 | ((cp >> 12) & 0x3F));
        out[(*used)++] = (char)(0x80 | ((cp >> 6) & 0x3F));
        out[(*used)++] = (char)(0x80 | (cp & 0x3F));
    }
}

static int copy_json_string(const char * src, char * out, size_t out_size)
{
    size_t used = 0;

    if(src == NULL || out == NULL || out_size == 0) {
        return -1;
    }

    while(*src && *src != '"') {
        if(used >= out_size - 1) {
            break;
        }

        if(*src == '\\') {
            src++;
            if(*src == '\0') {
                break;
            }

            switch(*src) {
                case '"':
                case '\\':
                case '/':
                    out[used++] = *src++;
                    break;
                case 'b':
                    out[used++] = '\b';
                    src++;
                    break;
                case 'f':
                    out[used++] = '\f';
                    src++;
                    break;
                case 'n':
                    out[used++] = '\n';
                    src++;
                    break;
                case 'r':
                    out[used++] = '\r';
                    src++;
                    break;
                case 't':
                    out[used++] = '\t';
                    src++;
                    break;
                case 'u': {
                    unsigned int cp;
                    if(read_hex4(src + 1, &cp)) {
                        append_utf8(out, out_size, &used, cp);
                        src += 5;
                    }
                    else {
                        src++;
                    }
                    break;
                }
                default:
                    out[used++] = *src++;
                    break;
            }
        }
        else {
            out[used++] = *src++;
        }
    }

    out[used] = '\0';
    return (*src == '"') ? 0 : -1;
}

static int json_extract_string(const char * json, const char * key, char * out, size_t out_size)
{
    char pattern[96];
    const char * start;

    snprintf(pattern, sizeof(pattern), "\"%s\"", key);
    start = strstr(json, pattern);
    if(start == NULL) {
        return -1;
    }

    start += strlen(pattern);
    start = strchr(start, ':');
    if(start == NULL) {
        return -1;
    }

    start++;
    while(*start == ' ' || *start == '\t' || *start == '\r' || *start == '\n') {
        start++;
    }

    if(*start != '"') {
        return -1;
    }

    start++;
    return copy_json_string(start, out, out_size);
}

static int json_extract_int(const char * json, const char * key, int * value)
{
    char pattern[96];
    const char * start;

    snprintf(pattern, sizeof(pattern), "\"%s\"", key);
    start = strstr(json, pattern);
    if(start == NULL) {
        return -1;
    }

    start += strlen(pattern);
    start = strchr(start, ':');
    if(start == NULL) {
        return -1;
    }

    start++;
    while(*start == ' ' || *start == '\t' || *start == '\r' || *start == '\n') {
        start++;
    }

    *value = atoi(start);
    return 0;
}

static int json_extract_asr_result(const char * json, char * out, size_t out_size)
{
    const char * pattern = "\"result\":[\"";
    const char * start = strstr(json, pattern);

    if(start == NULL) {
        return -1;
    }

    start += strlen(pattern);
    return copy_json_string(start, out, out_size);
}

static void json_escape(const char * src, char * out, size_t out_size)
{
    size_t used = 0;

    if(out_size == 0) {
        return;
    }

    while(src != NULL && *src && used < out_size - 1) {
        char ch = *src++;

        if(ch == '"' || ch == '\\') {
            if(used + 2 >= out_size) break;
            out[used++] = '\\';
            out[used++] = ch;
        }
        else if(ch == '\n') {
            if(used + 2 >= out_size) break;
            out[used++] = '\\';
            out[used++] = 'n';
        }
        else if(ch == '\r') {
            if(used + 2 >= out_size) break;
            out[used++] = '\\';
            out[used++] = 'r';
        }
        else if(ch == '\t') {
            if(used + 2 >= out_size) break;
            out[used++] = '\\';
            out[used++] = 't';
        }
        else {
            out[used++] = ch;
        }
    }

    out[used] = '\0';
}

static int run_command_capture(const char * cmd, char * output, size_t output_size)
{
    FILE * fp;
    char line[1024];

    if(output_size == 0) {
        return -1;
    }

    output[0] = '\0';
    fp = popen(cmd, "r");
    if(fp == NULL) {
        return -1;
    }

    while(fgets(line, sizeof(line), fp) != NULL) {
        append_text(output, output_size, line);
    }

    pclose(fp);
    return output[0] == '\0' ? -1 : 0;
}

static void write_text_file(const char * path, const char * text)
{
    FILE * fp = fopen(path, "w");
    if(fp == NULL) {
        return;
    }

    if(text != NULL) {
        fputs(text, fp);
    }

    fclose(fp);
}

static int read_file_capture(const char * path, char * output, size_t output_size)
{
    FILE * fp;
    char line[256];

    if(output_size == 0) {
        return -1;
    }

    output[0] = '\0';
    fp = fopen(path, "r");
    if(fp == NULL) {
        return -1;
    }

    while(fgets(line, sizeof(line), fp) != NULL) {
        append_text(output, output_size, line);
    }

    fclose(fp);
    return output[0] == '\0' ? -1 : 0;
}

static long file_size(const char * path)
{
    FILE * fp;
    long size;

    fp = fopen(path, "rb");
    if(fp == NULL) {
        return -1;
    }

    if(fseek(fp, 0, SEEK_END) != 0) {
        fclose(fp);
        return -1;
    }

    size = ftell(fp);
    fclose(fp);
    return size;
}

static unsigned short read_le16(const unsigned char * p)
{
    return (unsigned short)p[0] | ((unsigned short)p[1] << 8);
}

static unsigned int read_le32(const unsigned char * p)
{
    return (unsigned int)p[0] |
           ((unsigned int)p[1] << 8) |
           ((unsigned int)p[2] << 16) |
           ((unsigned int)p[3] << 24);
}

static void write_le16(unsigned char * p, unsigned short v)
{
    p[0] = (unsigned char)(v & 0xff);
    p[1] = (unsigned char)((v >> 8) & 0xff);
}

static void write_le32(unsigned char * p, unsigned int v)
{
    p[0] = (unsigned char)(v & 0xff);
    p[1] = (unsigned char)((v >> 8) & 0xff);
    p[2] = (unsigned char)((v >> 16) & 0xff);
    p[3] = (unsigned char)((v >> 24) & 0xff);
}

static int convert_stereo_wav_to_mono(const char * stereo_path, const char * mono_path)
{
    FILE * in;
    FILE * out;
    unsigned char riff[12];
    unsigned char chunk_header[8];
    unsigned char fmt[64];
    unsigned char out_header[44];
    unsigned int data_size = 0;
    long data_offset = -1;
    unsigned short audio_format = 0;
    unsigned short channels = 0;
    unsigned short bits_per_sample = 0;
    unsigned short block_align = 0;
    unsigned int source_rate = 0;
    unsigned int mono_data_size;
    unsigned int sample_count;
    unsigned int mono_sample_count;
    unsigned int acc = 0;

    in = fopen(stereo_path, "rb");
    if(in == NULL) {
        return -1;
    }

    if(fread(riff, 1, sizeof(riff), in) != sizeof(riff)) {
        fclose(in);
        return -1;
    }

    if(memcmp(riff, "RIFF", 4) != 0 || memcmp(riff + 8, "WAVE", 4) != 0) {
        fclose(in);
        return -1;
    }

    while(fread(chunk_header, 1, sizeof(chunk_header), in) == sizeof(chunk_header)) {
        unsigned int chunk_size = read_le32(chunk_header + 4);
        long chunk_data_pos = ftell(in);

        if(memcmp(chunk_header, "fmt ", 4) == 0) {
            unsigned int read_size = chunk_size;
            if(read_size > sizeof(fmt)) {
                read_size = sizeof(fmt);
            }

            if(fread(fmt, 1, read_size, in) != read_size) {
                fclose(in);
                return -1;
            }

            if(chunk_size > read_size && fseek(in, chunk_size - read_size, SEEK_CUR) != 0) {
                fclose(in);
                return -1;
            }

            audio_format = read_le16(fmt);
            channels = read_le16(fmt + 2);
            source_rate = read_le32(fmt + 4);
            block_align = read_le16(fmt + 12);
            bits_per_sample = read_le16(fmt + 14);
        }
        else if(memcmp(chunk_header, "data", 4) == 0) {
            data_offset = chunk_data_pos;
            data_size = chunk_size;
            if(fseek(in, chunk_size, SEEK_CUR) != 0) {
                fclose(in);
                return -1;
            }
        }
        else {
            if(fseek(in, chunk_size, SEEK_CUR) != 0) {
                fclose(in);
                return -1;
            }
        }

        if(chunk_size & 1) {
            fseek(in, 1, SEEK_CUR);
        }
    }

    if(audio_format != 1 ||
       bits_per_sample != 16 ||
       channels == 0 ||
       channels > 2 ||
       block_align == 0 ||
       block_align > sizeof((unsigned char[4]){0}) ||
       source_rate < 16000 ||
       data_offset < 0) {
        fclose(in);
        return -1;
    }

    sample_count = data_size / block_align;
    mono_sample_count = (unsigned int)(((unsigned long long)sample_count * 16000) / source_rate);
    mono_data_size = mono_sample_count * 2;

    out = fopen(mono_path, "wb");
    if(out == NULL) {
        fclose(in);
        return -1;
    }

    memset(out_header, 0, sizeof(out_header));
    memcpy(out_header, "RIFF", 4);
    write_le32(out_header + 4, 36 + mono_data_size);
    memcpy(out_header + 8, "WAVEfmt ", 8);
    write_le32(out_header + 16, 16);
    write_le16(out_header + 20, 1);
    write_le16(out_header + 22, 1);
    write_le32(out_header + 24, 16000);
    write_le32(out_header + 28, 16000 * 2);
    write_le16(out_header + 32, 2);
    write_le16(out_header + 34, 16);
    memcpy(out_header + 36, "data", 4);
    write_le32(out_header + 40, mono_data_size);

    if(fwrite(out_header, 1, sizeof(out_header), out) != sizeof(out_header)) {
        fclose(in);
        fclose(out);
        return -1;
    }

    if(fseek(in, data_offset, SEEK_SET) != 0) {
        fclose(in);
        fclose(out);
        return -1;
    }

    for(unsigned int i = 0; i < sample_count; i++) {
        unsigned char frame[4] = {0};
        unsigned char mono[2];
        short left;
        short right;
        short mixed;

        if(fread(frame, 1, block_align, in) != block_align) {
            fclose(in);
            fclose(out);
            return -1;
        }

        left = (short)read_le16(frame);
        right = channels == 2 ? (short)read_le16(frame + 2) : left;
        mixed = (short)(((int)left + (int)right) / 2);

        acc += 16000;
        if(acc >= source_rate) {
            acc -= source_rate;
            write_le16(mono, (unsigned short)mixed);

            if(fwrite(mono, 1, sizeof(mono), out) != sizeof(mono)) {
                fclose(in);
                fclose(out);
                return -1;
            }
        }
    }

    fclose(in);
    fclose(out);
    return 0;
}

static int baidu_speech_recognition(const char * audio_file, char * text, size_t text_size)
{
    char cmd[2048];
    char response[8192];
    char err_msg[256];
    int err_no = -1;

    snprintf(cmd, sizeof(cmd),
             "curl -s --connect-timeout 8 -m 25 -X POST -H \"Content-Type: audio/wav;rate=16000\" "
             "\"%s?dev_pid=%s&cuid=%s&token=%s\" --data-binary \"@%s\"",
             BAIDU_ASR_URL, BAIDU_DEV_PID, BAIDU_CUID, BAIDU_TOKEN, audio_file);

    if(run_command_capture(cmd, response, sizeof(response)) != 0) {
        snprintf(text, text_size,
                 "语音识别失败：curl 无响应。请测试：ping -c 3 vop.baidu.com; curl -I http://vop.baidu.com");
        return -1;
    }

    write_text_file(BAIDU_RESPONSE_LOG, response);

    if(json_extract_asr_result(response, text, text_size) == 0 && !is_blank_text(text)) {
        return 0;
    }

    json_extract_int(response, "err_no", &err_no);
    if(json_extract_string(response, "err_msg", err_msg, sizeof(err_msg)) == 0) {
        snprintf(text, text_size,
                 "语音识别失败：err_no=%d, err_msg=%s\n原始返回：/tmp/baidu_asr_response.txt",
                 err_no, err_msg);
    }
    else {
        snprintf(text, text_size,
                 "语音识别失败：未解析到有效结果\n返回前 200 字：%.200s\n原始返回：/tmp/baidu_asr_response.txt",
                 response);
    }

    return -1;
}

static int write_coze_request(const char * question, char * path, size_t path_size)
{
    FILE * fp;
    char escaped_question[2048];

    snprintf(path, path_size, "/tmp/coze_request_%ld_%d.json", (long)time(NULL), (int)getpid());
    fp = fopen(path, "w");
    if(fp == NULL) {
        return -1;
    }

    json_escape(question, escaped_question, sizeof(escaped_question));

    fprintf(fp,
            "{\"bot_id\":\"%s\",\"user_id\":\"%s\",\"stream\":true,"
            "\"additional_messages\":[{\"content\":\"%s\",\"content_type\":\"text\","
            "\"role\":\"user\",\"type\":\"question\"}],\"parameters\":{}}",
            COZE_BOT_ID, COZE_USER_ID, escaped_question);

    fclose(fp);
    return 0;
}

static int get_agent_answer(const char * question, char * answer, size_t answer_size)
{
    char request_path[128];
    char cmd[1024];
    char raw_preview[4096] = {0};
    char log_cmd[1280];
    char fallback_answer[4096] = {0};
    FILE * response_fp;

    answer[0] = '\0';
    if(write_coze_request(question, request_path, sizeof(request_path)) != 0) {
        snprintf(answer, answer_size, "智能体请求失败：无法创建临时请求文件");
        return -1;
    }

    write_text_file(COZE_RESPONSE_LOG, "");
    snprintf(cmd, sizeof(cmd),
             "curl -k -sS -N --connect-timeout 8 -m 60 -X POST '%s' "
             "-H \"Authorization: Bearer %s\" "
             "-H \"Content-Type: application/json\" "
             "--data-binary '@%s'",
             COZE_API_URL, COZE_TOKEN, request_path);

    snprintf(log_cmd, sizeof(log_cmd), "%s > %s 2>&1", cmd, COZE_RESPONSE_LOG);
    system(log_cmd);
    remove(request_path);

    if(read_file_capture(COZE_RESPONSE_LOG, raw_preview, sizeof(raw_preview)) != 0) {
        snprintf(answer, answer_size,
                 "智能体请求失败：curl 没有返回内容。请测试：curl -k -I https://api.coze.cn");
        return -1;
    }

    response_fp = fopen(COZE_RESPONSE_LOG, "r");
    if(response_fp != NULL) {
        char line[2048];
        char current_event[96] = {0};
        while(fgets(line, sizeof(line), response_fp) != NULL) {
            char chunk[1024];
            const char * data = line;
            bool is_answer_type;
            bool is_delta;
            bool is_completed;

            line[strcspn(line, "\r\n")] = '\0';
            if(strncmp(line, "event:", 6) == 0) {
                snprintf(current_event, sizeof(current_event), "%s", line + 6);
                continue;
            }

            if(strncmp(line, "data:", 5) == 0) {
                data = line + 5;
            }

            is_answer_type = strstr(data, "\"type\":\"answer\"") != NULL;
            is_delta = strcmp(current_event, "conversation.message.delta") == 0;
            is_completed = strcmp(current_event, "conversation.message.completed") == 0;

            if(!is_answer_type ||
               json_extract_string(data, "content", chunk, sizeof(chunk)) != 0 ||
               is_blank_text(chunk)) {
                continue;
            }

            if(is_delta) {
                append_text(answer, answer_size, chunk);
            }
            else if(is_completed && is_blank_text(fallback_answer)) {
                snprintf(fallback_answer, sizeof(fallback_answer), "%s", chunk);
            }
        }
        fclose(response_fp);
    }

    if(is_blank_text(answer) && !is_blank_text(fallback_answer)) {
        snprintf(answer, answer_size, "%s", fallback_answer);
    }

    if(!is_blank_text(answer)) {
        return 0;
    }

    {
        char chunk[1024];
        if(json_extract_string(raw_preview, "content", chunk, sizeof(chunk)) == 0 &&
           !is_blank_text(chunk) &&
           strstr(raw_preview, "\"type\":\"answer\"") != NULL) {
            snprintf(answer, answer_size, "%s", chunk);
            return 0;
        }
    }

    if(json_extract_string(raw_preview, "msg", answer, answer_size) == 0 && !is_blank_text(answer)) {
        char tmp[4096];
        snprintf(tmp, sizeof(tmp), "智能体请求失败：%s", answer);
        snprintf(answer, answer_size, "%s", tmp);
    }
    else {
        snprintf(answer, answer_size,
                 "智能体请求失败：未获取到回答\n返回前 500 字：%.500s\n原始返回：/tmp/coze_response.txt",
                 raw_preview);
    }

    return -1;
}

static void * record_worker(void * arg)
{
    char recognized[1024];
    char record_cmd[512];
    char record_error[768];
    int ret;
    bool conversion_failed = false;

    (void)arg;

    queue_status("正在录音，请说出需要提问的问题...");
    system("killall arecord 2>/dev/null");
    system("rm -f " RECORD_ERROR_LOG);
    system("rm -f " AUDIO_FILE " " STEREO_AUDIO_FILE);
    usleep(100000);

    snprintf(record_cmd, sizeof(record_cmd),
             "arecord -D plughw:0,0 -d %d -f S16_LE -r 16000 -c 1 %s >/dev/null 2>" RECORD_ERROR_LOG,
             RECORD_SECONDS, AUDIO_FILE);

    ret = system(record_cmd);
    if(ret != 0) {
        snprintf(record_cmd, sizeof(record_cmd),
                 "arecord -D plughw:0,0 -d %d -f S16_LE -r 48000 -c 2 %s >/dev/null 2>>" RECORD_ERROR_LOG,
                 RECORD_SECONDS, STEREO_AUDIO_FILE);
        conversion_failed = false;
        ret = system(record_cmd);
        if(ret == 0 && convert_stereo_wav_to_mono(STEREO_AUDIO_FILE, AUDIO_FILE) != 0) {
            ret = -1;
            conversion_failed = true;
        }
    }
    if(ret != 0) {
        snprintf(record_cmd, sizeof(record_cmd),
                 "arecord -D hw:0,0 -d %d -f S16_LE -r 48000 -c 2 %s >/dev/null 2>>" RECORD_ERROR_LOG,
                 RECORD_SECONDS, STEREO_AUDIO_FILE);
        conversion_failed = false;
        ret = system(record_cmd);
        if(ret == 0 && convert_stereo_wav_to_mono(STEREO_AUDIO_FILE, AUDIO_FILE) != 0) {
            ret = -1;
            conversion_failed = true;
        }
    }

    if(file_size(AUDIO_FILE) > 1024) {
        ret = 0;
        conversion_failed = false;
    }
    else if(file_size(STEREO_AUDIO_FILE) > 1024 &&
            convert_stereo_wav_to_mono(STEREO_AUDIO_FILE, AUDIO_FILE) == 0 &&
            file_size(AUDIO_FILE) > 1024) {
        ret = 0;
        conversion_failed = false;
    }

    if(ret != 0) {
        queue_status("录音失败：请检查麦克风和 arecord");
        if(conversion_failed) {
            queue_answer("录音成功，但 WAV 转换为 16000Hz 单声道失败。请在开发板执行：ls -l /tmp/assistant_question_stereo.wav");
        }
        else if(read_file_capture(RECORD_ERROR_LOG, record_error, sizeof(record_error)) == 0) {
            char msg[1024];
            snprintf(msg, sizeof(msg),
                     "录音失败，开发板返回：\n%s\n请测试：arecord -D plughw:0,0 -d 3 -f S16_LE -r 48000 -c 2 /tmp/test.wav",
                     record_error);
            queue_answer(msg);
        }
        else {
            queue_answer("录音失败：请检查麦克风是否可用，或确认 arecord 已安装。");
        }
        finish_job();
        return NULL;
    }

    queue_status("录音完成，正在调用百度语音识别...");
    if(baidu_speech_recognition(AUDIO_FILE, recognized, sizeof(recognized)) == 0) {
        char tip[1400];

        queue_question(recognized);
        snprintf(tip, sizeof(tip), "识别结果：%s\n\n请点击发送按钮提交给智能体。", recognized);
        queue_answer(tip);
        queue_status("识别完成，可点击发送按钮");
    }
    else {
        queue_answer(recognized);
        queue_status("语音识别失败");
    }

    finish_job();
    return NULL;
}

static void * send_worker(void * arg)
{
    char * question = (char *)arg;
    char answer[4096];

    queue_status("正在请求智能体，请稍候...");
    if(get_agent_answer(question, answer, sizeof(answer)) == 0) {
        queue_answer(answer);
        queue_status("回答完成");
    }
    else {
        queue_answer(answer);
        queue_status("智能体请求失败");
    }

    free(question);
    finish_job();
    return NULL;
}

void RecordAudio(lv_event_t * e)
{
    pthread_t tid;

    (void)e;
    printf("%s\n", assistant_build_mark);

    if(!try_begin_job()) {
        lv_label_set_text(ui_Label1, "当前任务正在执行，请稍候");
        return;
    }

    lv_textarea_set_text(ui_TextArea1, "");
    lv_textarea_set_text(ui_TextArea2, "正在录音，请说出需要提问的问题...");
    lv_label_set_text(ui_Label1, "正在录音...");

    if(pthread_create(&tid, NULL, record_worker, NULL) != 0) {
        lv_textarea_set_text(ui_TextArea2, "录音线程创建失败");
        lv_label_set_text(ui_Label1, "录音线程创建失败");
        finish_job();
        return;
    }

    pthread_detach(tid);
}

void StopRecording(lv_event_t * e)
{
    (void)e;
    system("killall arecord 2>/dev/null");
    lv_label_set_text(ui_Label1, "已停止录音");
}

void SendQuestion(lv_event_t * e)
{
    const char * question;
    char * question_copy;
    pthread_t tid;

    (void)e;

    if(!try_begin_job()) {
        lv_label_set_text(ui_Label1, "当前任务正在执行，请稍候");
        return;
    }

    question = lv_textarea_get_text(ui_TextArea1);
    if(is_blank_text(question)) {
        lv_textarea_set_text(ui_TextArea2, "请先通过语音输入问题，或在问题框中输入文字。");
        lv_label_set_text(ui_Label1, "问题为空");
        finish_job();
        return;
    }

    question_copy = duplicate_text(question);
    if(question_copy == NULL) {
        lv_textarea_set_text(ui_TextArea2, "内存不足，无法发送问题。");
        lv_label_set_text(ui_Label1, "发送失败");
        finish_job();
        return;
    }

    lv_textarea_set_text(ui_TextArea2, "问题已提交，正在等待智能体回答...");
    lv_label_set_text(ui_Label1, "正在请求智能体...");

    if(pthread_create(&tid, NULL, send_worker, question_copy) != 0) {
        free(question_copy);
        lv_textarea_set_text(ui_TextArea2, "智能体线程创建失败");
        lv_label_set_text(ui_Label1, "发送失败");
        finish_job();
        return;
    }

    pthread_detach(tid);
}

void assistant_ui_poll(void)
{
    bool update_status = false;
    bool update_question = false;
    bool update_answer = false;
    char status[sizeof(pending_status)];
    char question[sizeof(pending_question)];
    char answer[sizeof(pending_answer)];

    pthread_mutex_lock(&state_lock);

    if(dirty_status) {
        snprintf(status, sizeof(status), "%s", pending_status);
        dirty_status = false;
        update_status = true;
    }

    if(dirty_question) {
        snprintf(question, sizeof(question), "%s", pending_question);
        dirty_question = false;
        update_question = true;
    }

    if(dirty_answer) {
        snprintf(answer, sizeof(answer), "%s", pending_answer);
        dirty_answer = false;
        update_answer = true;
    }

    pthread_mutex_unlock(&state_lock);

    if(update_question && ui_TextArea1 != NULL) {
        lv_textarea_set_text(ui_TextArea1, question);
        lv_textarea_set_cursor_pos(ui_TextArea1, 0);
        lv_obj_scroll_to_y(ui_TextArea1, 0, LV_ANIM_OFF);
        lv_obj_invalidate(ui_TextArea1);
    }

    if(update_answer && ui_TextArea2 != NULL) {
        lv_textarea_set_text(ui_TextArea2, answer);
    }

    if(update_status && ui_Label1 != NULL) {
        lv_label_set_text(ui_Label1, status);
    }
}
