// This file was generated by SquareLine Studio and integrated for the course app.

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

void RecordAudio(lv_event_t * e);
void StopRecording(lv_event_t * e);
void SendQuestion(lv_event_t * e);
void assistant_ui_poll(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
